import type { Quad } from "./geometry";
import type { MethodId } from "./methods";

export type BlendMode = "source-over" | "multiply" | "screen" | "overlay" | "soft-light";
export type WrapMode = "plane" | "cylinder";
export type SurfaceTone = "light" | "mid" | "dark";
export type Category =
  | "Apparel"
  | "Drinkware"
  | "Packaging"
  | "Writing"
  | "Tech"
  | "Awards"
  | "Stationery"
  | "Display";

export type Mockup = {
  id: string;
  sku: string;
  name: string;
  category: Category;
  src: string;
  wrap: WrapMode;
  cylinderArc: number;
  quad: Quad;
  blend: BlendMode;
  invert: boolean;
  tone: SurfaceTone;
  surface: string;
  material: string;
  scale: number;
  maxScale: number;
  methods: MethodId[];
  defaultMethod: MethodId;
  printWmm: number;
  printHmm: number;
  substrate: string;
};

export const MOCKUPS: Mockup[] = [
  {
    id: "pen",
    sku: "TPX-PEN-01",
    name: "Metal twist pen",
    category: "Writing",
    src: "/mockups/pen.jpg",
    wrap: "cylinder",
    cylinderArc: 1.15,
    quad: [
      { x: 0.22, y: 0.43 },
      { x: 0.78, y: 0.39 },
      { x: 0.80, y: 0.56 },
      { x: 0.22, y: 0.60 },
    ],
    blend: "source-over",
    invert: false,
    tone: "dark",
    surface: "Barrel engrave zone",
    material: "coated black metal",
    scale: 0.88,
    maxScale: 0.96,
    methods: ["laser_engrave"],
    defaultMethod: "laser_engrave",
    printWmm: 50,
    printHmm: 6,
    substrate: "aluminum under black coat",
  },
  {
    id: "flask",
    sku: "TPX-FLK-01",
    name: "Stainless flask 8oz",
    category: "Drinkware",
    src: "/mockups/flask.jpg",
    wrap: "plane",
    cylinderArc: 0.4,
    quad: [
      { x: 0.34, y: 0.22 },
      { x: 0.66, y: 0.22 },
      { x: 0.66, y: 0.68 },
      { x: 0.34, y: 0.70 },
    ],
    blend: "source-over",
    invert: false,
    tone: "mid",
    surface: "Front body",
    material: "stainless steel",
    scale: 0.62,
    maxScale: 0.82,
    methods: ["laser_engrave"],
    defaultMethod: "laser_engrave",
    printWmm: 45,
    printHmm: 55,
    substrate: "brushed stainless",
  },
  {
    id: "usb",
    sku: "TPX-USB-01",
    name: "Metal USB 32GB",
    category: "Tech",
    src: "/mockups/usb.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.38, y: 0.30 },
      { x: 0.62, y: 0.30 },
      { x: 0.62, y: 0.62 },
      { x: 0.38, y: 0.62 },
    ],
    blend: "source-over",
    invert: false,
    tone: "mid",
    surface: "Body face",
    material: "aluminum",
    scale: 0.7,
    maxScale: 0.86,
    methods: ["laser_engrave"],
    defaultMethod: "laser_engrave",
    printWmm: 28,
    printHmm: 12,
    substrate: "brushed aluminum",
  },
  {
    id: "powerbank",
    sku: "TPX-PWR-01",
    name: "Aluminum power bank",
    category: "Tech",
    src: "/mockups/powerbank.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.24, y: 0.30 },
      { x: 0.76, y: 0.28 },
      { x: 0.76, y: 0.52 },
      { x: 0.24, y: 0.54 },
    ],
    blend: "source-over",
    invert: false,
    tone: "mid",
    surface: "Top face",
    material: "aluminum",
    scale: 0.58,
    maxScale: 0.8,
    methods: ["uv_print", "laser_engrave"],
    defaultMethod: "uv_print",
    printWmm: 90,
    printHmm: 30,
    substrate: "brushed aluminum",
  },
  {
    id: "award",
    sku: "TPX-AWD-01",
    name: "Crystal award",
    category: "Awards",
    src: "/mockups/award.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.30, y: 0.18 },
      { x: 0.70, y: 0.18 },
      { x: 0.70, y: 0.56 },
      { x: 0.30, y: 0.56 },
    ],
    blend: "source-over",
    invert: false,
    tone: "light",
    surface: "Crystal face",
    material: "crystal glass",
    scale: 0.55,
    maxScale: 0.78,
    methods: ["laser_engrave"],
    defaultMethod: "laser_engrave",
    printWmm: 70,
    printHmm: 90,
    substrate: "frosted crystal",
  },
  {
    id: "mug",
    sku: "TPX-MUG-01",
    name: "White ceramic mug",
    category: "Drinkware",
    src: "/mockups/mug.jpg",
    wrap: "cylinder",
    cylinderArc: 1.55,
    quad: [
      { x: 0.18, y: 0.36 },
      { x: 0.40, y: 0.34 },
      { x: 0.42, y: 0.64 },
      { x: 0.17, y: 0.62 },
    ],
    blend: "multiply",
    invert: false,
    tone: "light",
    surface: "Glazed wall",
    material: "ceramic",
    scale: 0.55,
    maxScale: 0.78,
    methods: ["sublimation"],
    defaultMethod: "sublimation",
    printWmm: 80,
    printHmm: 70,
    substrate: "polymer coat",
  },
  {
    id: "cup",
    sku: "TPX-CUP-01",
    name: "Paper cup",
    category: "Drinkware",
    src: "/mockups/cup.jpg",
    wrap: "cylinder",
    cylinderArc: 1.45,
    quad: [
      { x: 0.30, y: 0.28 },
      { x: 0.68, y: 0.30 },
      { x: 0.70, y: 0.50 },
      { x: 0.28, y: 0.48 },
    ],
    blend: "multiply",
    invert: false,
    tone: "light",
    surface: "Wall above sleeve",
    material: "paper",
    scale: 0.58,
    maxScale: 0.8,
    methods: ["uv_print"],
    defaultMethod: "uv_print",
    printWmm: 70,
    printHmm: 40,
    substrate: "coated paper",
  },
  {
    id: "notebook",
    sku: "TPX-NTB-01",
    name: "Hardcover notebook",
    category: "Stationery",
    src: "/mockups/notebook.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.20, y: 0.16 },
      { x: 0.72, y: 0.20 },
      { x: 0.78, y: 0.86 },
      { x: 0.22, y: 0.90 },
    ],
    blend: "source-over",
    invert: true,
    tone: "dark",
    surface: "Front cover",
    material: "cloth",
    scale: 0.48,
    maxScale: 0.7,
    methods: ["uv_print", "laser_engrave"],
    defaultMethod: "uv_print",
    printWmm: 90,
    printHmm: 140,
    substrate: "cover boards",
  },
  {
    id: "polo",
    sku: "TPX-POL-01",
    name: "Navy polo",
    category: "Apparel",
    src: "/mockups/polo.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.36, y: 0.33 },
      { x: 0.52, y: 0.34 },
      { x: 0.52, y: 0.46 },
      { x: 0.36, y: 0.46 },
    ],
    blend: "source-over",
    invert: true,
    tone: "dark",
    surface: "Left chest",
    material: "pique cotton",
    scale: 0.78,
    maxScale: 0.92,
    methods: ["embroidery", "uv_dtf"],
    defaultMethod: "embroidery",
    printWmm: 80,
    printHmm: 50,
    substrate: "pique",
  },
  {
    id: "tshirt",
    sku: "TPX-TEE-01",
    name: "White tee",
    category: "Apparel",
    src: "/mockups/tshirt.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.34, y: 0.27 },
      { x: 0.62, y: 0.28 },
      { x: 0.63, y: 0.48 },
      { x: 0.33, y: 0.47 },
    ],
    blend: "multiply",
    invert: false,
    tone: "light",
    surface: "Chest panel",
    material: "cotton",
    scale: 0.68,
    maxScale: 0.84,
    methods: ["embroidery", "uv_dtf"],
    defaultMethod: "embroidery",
    printWmm: 280,
    printHmm: 350,
    substrate: "jersey",
  },
  {
    id: "hoodie",
    sku: "TPX-HOD-01",
    name: "Hoodie",
    category: "Apparel",
    src: "/mockups/hoodie.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.34, y: 0.32 },
      { x: 0.63, y: 0.33 },
      { x: 0.64, y: 0.51 },
      { x: 0.33, y: 0.50 },
    ],
    blend: "screen",
    invert: true,
    tone: "dark",
    surface: "Chest panel",
    material: "fleece",
    scale: 0.7,
    maxScale: 0.84,
    methods: ["embroidery", "uv_dtf"],
    defaultMethod: "embroidery",
    printWmm: 280,
    printHmm: 320,
    substrate: "fleece",
  },
  {
    id: "cap",
    sku: "TPX-CAP-01",
    name: "Canvas cap",
    category: "Apparel",
    src: "/mockups/cap.jpg",
    wrap: "cylinder",
    cylinderArc: 0.95,
    quad: [
      { x: 0.38, y: 0.26 },
      { x: 0.64, y: 0.30 },
      { x: 0.66, y: 0.50 },
      { x: 0.36, y: 0.52 },
    ],
    blend: "multiply",
    invert: false,
    tone: "mid",
    surface: "Front crown",
    material: "canvas",
    scale: 0.7,
    maxScale: 0.86,
    methods: ["embroidery", "uv_dtf"],
    defaultMethod: "embroidery",
    printWmm: 90,
    printHmm: 50,
    substrate: "twill",
  },
  {
    id: "tote",
    sku: "TPX-TOT-01",
    name: "Canvas tote",
    category: "Packaging",
    src: "/mockups/tote.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.24, y: 0.36 },
      { x: 0.74, y: 0.37 },
      { x: 0.72, y: 0.84 },
      { x: 0.22, y: 0.86 },
    ],
    blend: "multiply",
    invert: false,
    tone: "light",
    surface: "Front panel",
    material: "canvas",
    scale: 0.56,
    maxScale: 0.78,
    methods: ["uv_print"],
    defaultMethod: "uv_print",
    printWmm: 250,
    printHmm: 280,
    substrate: "canvas",
  },
  {
    id: "bag",
    sku: "TPX-BAG-01",
    name: "Shopping bag",
    category: "Packaging",
    src: "/mockups/bag.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.24, y: 0.34 },
      { x: 0.72, y: 0.36 },
      { x: 0.70, y: 0.82 },
      { x: 0.22, y: 0.84 },
    ],
    blend: "multiply",
    invert: false,
    tone: "mid",
    surface: "Front panel",
    material: "paper",
    scale: 0.56,
    maxScale: 0.78,
    methods: ["uv_print"],
    defaultMethod: "uv_print",
    printWmm: 220,
    printHmm: 280,
    substrate: "kraft paper",
  },
  {
    id: "box",
    sku: "TPX-BOX-01",
    name: "Kraft gift box",
    category: "Packaging",
    src: "/mockups/box.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.28, y: 0.42 },
      { x: 0.52, y: 0.48 },
      { x: 0.50, y: 0.82 },
      { x: 0.26, y: 0.78 },
    ],
    blend: "multiply",
    invert: false,
    tone: "mid",
    surface: "Lid face",
    material: "cardboard",
    scale: 0.58,
    maxScale: 0.8,
    methods: ["uv_print"],
    defaultMethod: "uv_print",
    printWmm: 120,
    printHmm: 80,
    substrate: "kraft board",
  },
  {
    id: "totem",
    sku: "TPX-TTM-01",
    name: "Indoor totem",
    category: "Display",
    src: "/mockups/totem.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.29, y: 0.10 },
      { x: 0.69, y: 0.10 },
      { x: 0.74, y: 0.78 },
      { x: 0.26, y: 0.78 },
    ],
    blend: "multiply",
    invert: false,
    tone: "light",
    surface: "Print face",
    material: "lightbox panel",
    scale: 0.62,
    maxScale: 0.88,
    methods: ["uv_print"],
    defaultMethod: "uv_print",
    printWmm: 500,
    printHmm: 1500,
    substrate: "backlit PET",
  },
  {
    id: "billboard",
    sku: "TPX-BLB-01",
    name: "Urban billboard",
    category: "Display",
    src: "/mockups/billboard.jpg",
    wrap: "plane",
    cylinderArc: 0,
    quad: [
      { x: 0.08, y: 0.16 },
      { x: 0.92, y: 0.16 },
      { x: 0.92, y: 0.62 },
      { x: 0.08, y: 0.68 },
    ],
    blend: "multiply",
    invert: false,
    tone: "light",
    surface: "Poster face",
    material: "vinyl",
    scale: 0.72,
    maxScale: 0.92,
    methods: ["uv_print"],
    defaultMethod: "uv_print",
    printWmm: 6000,
    printHmm: 3000,
    substrate: "outdoor vinyl",
  },
];

export const SAMPLE_LOGOS = [
  { id: "north", name: "North", src: "/logos/north.svg" },
  { id: "orbit", name: "Orbit", src: "/logos/orbit.svg" },
  { id: "plane", name: "Plane", src: "/logos/plane.svg" },
  { id: "bars", name: "Bars", src: "/logos/bars.svg" },
] as const;
